In [1]:
import pandas as pd

In [2]:
def mergeDF(df1, df2):
    winRate1 = df1['winRate']
    winRate2 = df2['winRate']
    winRate = (winRate1 + winRate2) / 2
    df = df1.copy()
    df['winRate'] = winRate
    return df

In [4]:
pd.read_csv('raw data/Iteration 3/it3-6E-run2.csv')

        ID  p31  p32  p33  p34  p35  p36  winRate
0        0  0.0  0.0  0.0  0.0  0.0  1.0   0.6790
1        1  0.0  0.0  0.0  0.0  0.1  0.9   0.6652
2        2  0.0  0.0  0.0  0.0  0.2  0.8   0.6744
3        3  0.0  0.0  0.0  0.0  0.3  0.7   0.6714
4        4  0.0  0.0  0.0  0.0  0.4  0.6   0.6798
...    ...  ...  ...  ...  ...  ...  ...      ...
2998  2998  0.9  0.0  0.0  0.0  0.1  0.0   0.7134
2999  2999  0.9  0.0  0.0  0.1  0.0  0.0   0.3944
3000  3000  0.9  0.0  0.1  0.0  0.0  0.0   0.6054
3001  3001  0.9  0.1  0.0  0.0  0.0  0.0   0.7202
3002  3002  1.0  0.0  0.0  0.0  0.0  0.0   0.5064

[3003 rows x 8 columns]

In [8]:
iteration = ['2', '3']
experiment = ['1', '2', '3', '4', '6']
player = ['E']
run = ['1', '2']

In [16]:
for i in iteration:
    for e in experiment:
        for p in player:
            path1 = 'raw data/Iteration ' + i + '/it' + i + '-' + e + p + '-run' + '1' + '.csv'
            path2 = 'raw data/Iteration ' + i + '/it' + i + '-' + e + p + '-run' + '2' + '.csv'
            data1 = pd.read_csv(path1)
            data2 = pd.read_csv(path2)
            data = mergeDF(data1, data2)
            path = 'it' + i + '-' + e + p + '.csv'
            print(path1, path2, path)
            data.to_csv(path, index = False)

raw data/Iteration 2/it2-1E-run1.csv raw data/Iteration 2/it2-1E-run2.csv it2-1E.csv
raw data/Iteration 2/it2-2E-run1.csv raw data/Iteration 2/it2-2E-run2.csv it2-2E.csv
raw data/Iteration 2/it2-3E-run1.csv raw data/Iteration 2/it2-3E-run2.csv it2-3E.csv
raw data/Iteration 2/it2-4E-run1.csv raw data/Iteration 2/it2-4E-run2.csv it2-4E.csv
raw data/Iteration 2/it2-6E-run1.csv raw data/Iteration 2/it2-6E-run2.csv it2-6E.csv
raw data/Iteration 3/it3-1E-run1.csv raw data/Iteration 3/it3-1E-run2.csv it3-1E.csv
raw data/Iteration 3/it3-2E-run1.csv raw data/Iteration 3/it3-2E-run2.csv it3-2E.csv
raw data/Iteration 3/it3-3E-run1.csv raw data/Iteration 3/it3-3E-run2.csv it3-3E.csv
raw data/Iteration 3/it3-4E-run1.csv raw data/Iteration 3/it3-4E-run2.csv it3-4E.csv
raw data/Iteration 3/it3-6E-run1.csv raw data/Iteration 3/it3-6E-run2.csv it3-6E.csv